### ISSUE TITLE
run demo.py happen some question

### ISSUE THREAD

**Issue by lucker26** [NVlabs/GOHA#2]
(pytorch-openpose-master) E:\GOHA-master\GOHA-master\src>python demo.py --config configs/s2.yml --checkpoint logs/s3/checkpoint825000.ckpt --savedir /raid/test --source_path /raid/goha_demo_data/celeba --target_path /raid/goha_demo_data/person_2_test --frame_limit 100
source_path: /raid/goha_demo_data/celeba
target_path: /raid/goha_demo_data/person_2_test
Found 0 videos with 0 frames in total.
Found 0 videos with 0 frames in total.
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /nvidia/segformer-b0-finetuned-ade-512-512/resolve/main/config.json (Caused by
 ProxyError('Unable to connect to proxy', OSError(0, 'Error')))"), '(Request ID: 206591bb-11a3-4e50-a3e1-2514055b7a98)')' thrown while requesting HEAD https://huggingface.co/nvidia/segformer-b0-finetuned-ade-512-512/resolve/main/config.json
Traceback (most recent call last):
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connectionpool.py", line 777, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connectionpool.py", line 1046, in _prepare_proxy
    conn.connect()
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connection.py", line 619, in connect
    self.sock = sock = self._connect_tls_proxy(self.host, sock)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connection.py", line 692, in _connect_tls_proxy
    tls_in_tls=False,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connection.py", line 793, in _ssl_wrap_socket_and_match_hostname
    tls_in_tls=tls_in_tls,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError(0, 'Error'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\connectionpool.py", line 846, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /nvidia/segformer-b0-finetuned-ade-512-512/resolve/main/config.json (Caused by ProxyError('Unable to connect to proxy', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 246, in <module>
    main()
  File "demo.py", line 242, in main
    tester.define_model(configargs.checkpoint)
  File "demo.py", line 79, in define_model
    model = mod.Model(cfg, test = True)
  File "E:\GOHA-master\GOHA-master\src\models\model_s2.py", line 34, in __init__
    self.template_net = SegformerForSemanticSegmentation.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512")
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\transformers\modeling_utils.py", line 2318, in from_pretrained
    **kwargs,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\transformers\configuration_utils.py", line 641, in _get_config_dict
    _commit_hash=commit_hash,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
    local_files_only=local_files_only,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\file_download.py", line 1199, in hf_hub_download
    timeout=etag_timeout,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\file_download.py", line 1539, in get_hf_file_metadata
    timeout=timeout,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\file_download.py", line 415, in _request_wrapper
    **params,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\file_download.py", line 451, in _request_wrapper
    **params,
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\utils\_http.py", line 274, in http_backoff
    raise err
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\utils\_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\lenovo\.conda\envs\pytorch-openpose-master\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /nvidia/segformer-b0-finetuned-ade-512-512/resolve/main/config.json (Caused by ProxyError('Unable to connect to proxy', OSError(0, 'Error')))"), '(Request ID: 206591bb-11a3-4e50-a3e1-2514055b7a98)')

**Comment by sunshineatnoon** [comment]
Yes, the code didn't find source and target images. But the error is from hugging face. Can you access https://huggingface.co/nvidia/segformer-b0-finetuned-ade-512-512/resolve/main/config.json?
