### ISSUE TITLE
Unable to run the Demo

### ISSUE THREAD

**Issue by Andyshen555** [NVlabs/GOHA#5]
After I set up the environment using install.sh and downloaded all the external dependencies, I tried to run the demo with the provided command ```python demo.py --config configs/s2.yml --checkpoint logs/s3/checkpoint825000.ckpt --savedir ../test --source_path ../goha_demo_data/celeba/ --target_path ../goha_demo_data/HDTF/``` The program throws an error ```No such file or directory: '/xtli-correspondence/OMG/HRN/assets/3dmm_assets/template_mesh/bfm_uvs2.npy'``` With the full log below.

Am I missing some libraries or necessary step to run the Demo? Please help. Thanks in advance.

--------------------------------------------------------------------------------------------------------------------------------------------------x
Found 1 videos with 1 frames in total.
Found 1 videos with 1000 frames in total.
Loading Deep3D encoder
model [FaceReconModel] was created
loading the model from ../external/Deep3DFaceRecon/checkpoints/face_recon_feat0.2_augment/epoch_20.pth
Traceback (most recent call last):
  File "/mnt/ssd/FrameInterpolation/Training/GOHA/src/demo.py", line 244, in <module>
    main()
  File "/mnt/ssd/FrameInterpolation/Training/GOHA/src/demo.py", line 240, in main
    tester.define_model(configargs.checkpoint)
  File "/mnt/ssd/FrameInterpolation/Training/GOHA/src/demo.py", line 77, in define_model
    model = mod.Model(cfg, test = True)
  File "/mnt/ssd/FrameInterpolation/Training/GOHA/src/models/model_s2.py", line 104, in __init__
    self.exp_loss_fn = ExpLoss(cfg.device, test)
  File "/mnt/ssd/FrameInterpolation/Training/GOHA/src/losses/threeDMM.py", line 41, in __init__
    self.bfm_UVs = np.load('/xtli-correspondence/OMG/HRN/assets/3dmm_assets/template_mesh/bfm_uvs2.npy')
  File "/home/yezhi/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/xtli-correspondence/OMG/HRN/assets/3dmm_assets/template_mesh/bfm_uvs2.npy'

**Comment by three-bee** [comment]
You can use bfm_uvs2.npy from [here](https://github.com/youngLBW/HRN/blob/main/assets/README.md) and replace the path.
